goofing around

diff --git a/.github/workflows/upload-coverage-report.yml b/.github/workflows/upload-coverage-report.yml
--- a/.github/workflows/upload-coverage-report.yml
+++ b/.github/workflows/upload-coverage-report.yml
@@ -19,38 +19,53 @@ jobs:
     concurrency:
       group: "pages"
       cancel-in-progress: false
-    strategy:
-      matrix:
-        spec:
-            - .github/workflows/dotnet-windows.yml codecoverage-report-windows-net8.0-Release, codecoverage-report-windows-net481-Release
-            - .github/workflows/dotnet-ubuntu.yml codecoverage-report-ubuntu-net8.0-Release
+
+    env:
+      WORKFLOW_SPEC: |
+        dotnet-windows.yml: codecoverage-report-windows-net8.0-Release,codecoverage-report-windows-net481-Release
+        dotnet-ubuntu.yml:  codecoverage-report-ubuntu-net8.0-Release
     steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0 # avoid shallow clone so that nbgv can do its work.
+
     - name: 'Download latest successful build artifact'
       run: |
-        IFS=' ' read -ra spec <<< "${{ matrix.spec }}"
-        workflow_id=$(echo ${spec[0]} | xargs)
-        run_id=$(gh run list -w $workflow_id --json conclusion,headBranch,databaseId --jq 'first(.[] | select(.conclusion | contains("success"))) | .databaseId')
-        [ -z "$run_id" ] && echo "::error:::No successful run found for workflow '$workflow_id'" && exit 1 || true
-        echo "::notice::Last successful run for workflow '$workflow_id' is '$run_id'"
-        IFS=',' read -ra artifacts <<< "${spec[@]:1}"
-        for i in "${artifacts[@]}"; do
-          artifact_id=$(echo $i | xargs)
-          artifact_subdir=$(echo $artifact_id | sed 's/codecoverage-report-//g')
-          echo "::notice::Downloading '$artifact_id'"
-          gh run download $run_id -n $artifact_id -D $ARTIFACTS_TMP_DIR
-          unzip $ARTIFACTS_TMP_DIR/${artifact_id}.zip -d $OUTPUT_DIR/$artifact_subdir
+        IFS='\n' read -ra wsspec <<< "${{ env.WORKFLOW_SPEC }}"
+        for ispec in "${wsspec[@]}"; do
+            IFS=':' read -ra spec <<< "$ispec"
+            workflow_id=$(echo ${spec[0]} | xargs)
+
+            echo "Getting last successful run for workflow '$workflow_id'"
+
+            run_id=$(gh run list -w $workflow_id --json conclusion,headBranch,databaseId --jq 'first(.[] | select(.conclusion | contains("success"))) | .databaseId')
+            if [ -z "$run_id" ]; do
+              echo "::error:::No successful run found for workflow '$workflow_id'" 1>&2
+              exit 1
+            fi
+            echo "Last successful run for workflow '$workflow_id' is '$run_id'"
+
+            IFS=',' read -ra artifacts <<< "${spec[@]:1}"
+            for i in "${artifacts[@]}"; do
+                artifact_id=$(echo $i | xargs)
+                artifact_subdir=$(echo $artifact_id | sed 's/codecoverage-report-//g')
+                echo "Downloading '$artifact_id'"
+                gh run download $run_id -n $artifact_id -D $ARTIFACTS_TMP_DIR
+                unzip $ARTIFACTS_TMP_DIR/${artifact_id}.zip -d $OUTPUT_DIR/$artifact_subdir
+            done
         done
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         WF_SPEC: ${{ matrix.spec }}
         ARTIFACTS_TMP_DIR: artifacts
         OUTPUT_DIR: coverage-results
-    - name: Setup Pages
-      uses: actions/configure-pages@v5
-    - name: Upload Pages
-      uses: actions/upload-pages-artifact@v3        
-      with:
-        path: coverage-results
-    - name: Deploy Pages
-      id: deployment
-      uses: actions/deploy-pages@v4
+    # - name: Setup Pages
+    #   uses: actions/configure-pages@v5
+    # - name: Upload Pages
+    #   uses: actions/upload-pages-artifact@v3        
+    #   with:
+    #     path: coverage-results
+    # - name: Deploy Pages
+    #   id: deployment
+    #   uses: actions/deploy-pages@v4
