goofing around

diff --git a/.github/workflows/upload-coverage-report.yml b/.github/workflows/upload-coverage-report.yml
--- a/.github/workflows/upload-coverage-report.yml
+++ b/.github/workflows/upload-coverage-report.yml
@@ -33,9 +33,7 @@ jobs:
     - name: 'Download latest successful build artifact'
       run: |
         IFS='|' read -ra wsspec <<< "${{ env.WORKFLOW_SPEC }}"
-        echo $wsspec
         for ispec in "${wsspec[@]}"; do
-            echo $ispec
             IFS=':' read -ra spec <<< "$ispec"
             workflow_id=$(echo ${spec[0]} | xargs)
 
@@ -43,7 +41,7 @@ jobs:
 
             run_id=$(gh run list -w $workflow_id --json conclusion,headBranch,databaseId --jq 'first(.[] | select(.conclusion | contains("success"))) | .databaseId')
             if [ -z "$run_id" ]; then
-              echo "::error:::No successful run found for workflow '$workflow_id'" 1>&2
+              echo "::error::No successful run found for workflow '$workflow_id'" 1>&2
               exit 1
             fi
             echo "Last successful run for workflow '$workflow_id' is '$run_id'"
@@ -52,8 +50,15 @@ jobs:
             for i in "${artifacts[@]}"; do
                 artifact_id=$(echo $i | xargs)
                 artifact_subdir=$(echo $artifact_id | sed 's/codecoverage-report-//g')
-                echo "Downloading '$artifact_id'"
+
+                echo "Downloading artifact '$artifact_id' for workflow '$workflow_id'"
                 gh run download $run_id -n $artifact_id -D $ARTIFACTS_TMP_DIR
+                if [ $? -ne 0 ]; then
+                    echo "::error::Failed to download artifact '$artifact_id' for workflow '$workflow_id'" 1>&2
+                    exit 1
+                fi
+
+                echo "Unzip artifact '${artifact_id}.zip' into '$OUTPUT_DIR/$artifact_subdir'"
                 unzip $ARTIFACTS_TMP_DIR/${artifact_id}.zip -d $OUTPUT_DIR/$artifact_subdir
             done
         done
